import { Router } from 'express';
import { authRouter } from './auth.js';
import { bootstrapRouter } from './bootstrap.js';
import { resetRouter } from './reset.js';
import { leadsRouter } from './leads.js';
import { contactsRouter } from './contacts.js';
import { accountsRouter } from './accounts.js';
import { dealsRouter } from './deals.js';
import { productsRouter } from './products.js';
import { ticketsRouter } from './tickets.js';
import { campaignsRouter } from './campaigns.js';
import { quotesRouter } from './quotes.js';
import { usersRouter } from './users.js';
import { tasksRouter } from './tasks.js';
import { activitiesRouter } from './activities.js';
import { notificationsRouter } from './notifications.js';
import { customFieldDefsRouter } from './customFieldDefs.js';
import { layoutsRouter } from './layouts.js';
import { auditRouter } from './audit.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/bootstrap', bootstrapRouter);
apiRouter.use('/reset', resetRouter);
apiRouter.use('/leads', leadsRouter);
apiRouter.use('/contacts', contactsRouter);
apiRouter.use('/accounts', accountsRouter);
apiRouter.use('/deals', dealsRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/tickets', ticketsRouter);
apiRouter.use('/campaigns', campaignsRouter);
apiRouter.use('/quotes', quotesRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/tasks', tasksRouter);
apiRouter.use('/activities', activitiesRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/customFieldDefs', customFieldDefsRouter);
apiRouter.use('/layouts', layoutsRouter);
apiRouter.use('/audit', auditRouter);
